new validation

diff --git a/.github/workflows/bump_version.yml b/.github/workflows/bump_version.yml
--- a/.github/workflows/bump_version.yml
+++ b/.github/workflows/bump_version.yml
@@ -42,23 +42,27 @@ jobs:
 
           ## Getting version info from Git Tag
           HASH=$(git rev-parse HEAD)
-          #version_git_tag=$(git describe --match ${MAJOR_MINOR_VERSION}.* 2> /dev/null)
-          #if [ $? -eq 0 ]; then
-          version_git_tag=$(curl --silent \
-                              -H "Accept: application/vnd.github+json" \
-                              -H "Authorization: Bearer ${BOT_TOKEN}" \
-                              -H "X-GitHub-Api-Version: 2022-11-28" \
-                              https://api.github.com/repos/${{ github.repository }}/releases/latest | grep 'tag_name' | awk  -F'"' '{print $4}' \
-                            )
-          if [ -z "${version_git_tag}" ]; then
-              echo "Major and minor version not found in Git. Creating new version tag..."
-              VERSION=${MAJOR_MINOR_VERSION}.${DEFAULT_BUILD_VERSION}
-          else
+          # version_git_tag=$(git describe --match ${MAJOR_MINOR_VERSION}.* 2> /dev/null)
+          version_git_tag=$(git describe --match ${MAJOR_MINOR_VERSION}.*)
+          if [ $? -eq 0 ]; then
+          # version_git_tag=$(curl --silent \
+          #                     -H "Accept: application/vnd.github+json" \
+          #                     -H "Authorization: Bearer ${BOT_TOKEN}" \
+          #                     -H "X-GitHub-Api-Version: 2022-11-28" \
+          #                     https://api.github.com/repos/${{ github.repository }}/releases/latest | grep 'tag_name' | awk  -F'"' '{print $4}' \
+          #                   )
+          # if [ -z "${version_git_tag}" ]; then
+          #     echo "Major and minor version not found in Git. Creating new version tag..."
+          #     VERSION=${MAJOR_MINOR_VERSION}.${DEFAULT_BUILD_VERSION}
+          # else
               echo "Version found in Git: ${version_git_tag}"
               re="[0-9]+\.[0-9]+\.([0-9]+)"
               [[ $version_git_tag =~ $re ]]
               build=$((BASH_REMATCH[1]+1))
               VERSION=${MAJOR_MINOR_VERSION}.${build}
+          else
+              echo "Major and minor version not found in Git. Creating new version tag..."
+              VERSION=${MAJOR_MINOR_VERSION}.${DEFAULT_BUILD_VERSION}
           fi
           echo "Setting version to ${VERSION} with hash ${HASH}"
 
